import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'package:uuid/uuid.dart';

void main() => runApp(const JarvisApp());

class JarvisApp extends StatefulWidget { const JarvisApp({super.key}); @override State<JarvisApp> createState()=>_JarvisAppState(); }
class _JarvisAppState extends State<JarvisApp> {
  ThemeMode mode=ThemeMode.dark;
  final prefs=Prefs();
  @override Widget build(BuildContext c)=>MaterialApp(title:'JARVIS NEO Mobile',debugShowCheckedModeBanner:false,themeMode:mode,
    darkTheme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:Colors.cyan,brightness:Brightness.dark),scaffoldBackgroundColor:const Color(0xff070b12)),
    theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:Colors.cyan),scaffoldBackgroundColor:const Color(0xfff4f7fb)),
    home:Home(onTheme:(v)=>setState(()=>mode=v?ThemeMode.light:ThemeMode.dark)));
}

class Home extends StatefulWidget { final ValueChanged<bool> onTheme; const Home({super.key,required this.onTheme}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  int tab=0; final tts=FlutterTts(); final chat=ChatService(); final log=ActivityLog();
  final pages=['Command','Devices','Files','Routines','Sentinel','Settings'];
  @override Widget build(BuildContext c){ final body=[CommandPage(chat:chat,tts:tts,log:log),const DevicesPage(),const FilesPage(),const RoutinesPage(),const SentinelPage(),SettingsPage(onTheme:widget.onTheme)];
    return Scaffold(appBar:AppBar(title:Row(children:[Container(width:10,height:10,decoration:BoxDecoration(shape:BoxShape.circle,color:Colors.cyan,boxShadow:[BoxShadow(color:Colors.cyan.withOpacity(.8),blurRadius:12)])),const SizedBox(width:10),Text('J.A.R.V.I.S. NEO',style:const TextStyle(fontWeight:FontWeight.w700,letterSpacing:1.2))]),actions:[IconButton(onPressed:()=>setState(()=>tab=5),icon:const Icon(Icons.settings_outlined))]),
      body:body[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.mic_none),selectedIcon:Icon(Icons.mic),label:'JARVIS'),NavigationDestination(icon:Icon(Icons.devices_other),label:'Devices'),NavigationDestination(icon:Icon(Icons.folder_open),label:'Files'),NavigationDestination(icon:Icon(Icons.auto_awesome),label:'Routines'),NavigationDestination(icon:Icon(Icons.shield_outlined),label:'Sentinel'),NavigationDestination(icon:Icon(Icons.tune),label:'Settings') ])); }
}

class CommandPage extends StatefulWidget { final ChatService chat; final FlutterTts tts; final ActivityLog log; const CommandPage({super.key,required this.chat,required this.tts,required this.log}); @override State<CommandPage> createState()=>_CommandPageState(); }
class _CommandPageState extends State<CommandPage>{ final input=TextEditingController(); final messages=<Map<String,String>>[]; bool busy=false;
  Future<void> send() async { final q=input.text.trim(); if(q.isEmpty||busy)return; input.clear(); setState(()=>messages.add({'role':'user','text':q})); busy=true; setState((){}); final a=await widget.chat.ask(q); widget.log.add('AI','Conversation'); setState(()=>messages.add({'role':'jarvis','text':a})); busy=false; if(await Prefs().getBool('voice',true)) widget.tts.speak(a); setState((){}); }
  @override Widget build(BuildContext c)=>Column(children:[Expanded(child:messages.isEmpty?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.auto_awesome,size:72,color:Colors.cyan.withOpacity(.75)),const SizedBox(height:18),const Text('Bonjour. JARVIS NEO Mobile est opérationnel.',style:TextStyle(fontSize:18)),const SizedBox(height:8),Text('Commande vocale, appareils, fichiers et automatisations.',style:TextStyle(color:Colors.grey))])):ListView.builder(padding:const EdgeInsets.all(16),itemCount:messages.length,itemBuilder:(c,i){final m=messages[i];final user=m['role']=='user';return Align(alignment:user?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),constraints:BoxConstraints(maxWidth:MediaQuery.of(c).size.width*.82),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),color:user?Colors.cyan.withOpacity(.18):Colors.white.withOpacity(.06),border:Border.all(color:user?Colors.cyan.withOpacity(.25):Colors.white.withOpacity(.08))),child:Text(m['text']!)));})),
    SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(12,8,12,12),child:Row(children:[Expanded(child:TextField(controller:input,onSubmitted:(_)=>send(),decoration:InputDecoration(hintText:'Parler à JARVIS…',prefixIcon:const Icon(Icons.chat_bubble_outline),filled:true,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none)))),const SizedBox(width:8),FloatingActionButton(onPressed:busy?null:send,child:busy?const SizedBox(width:22,height:22,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.arrow_upward))])))]);
}

class ChatService { Future<String> ask(String text) async { final p=await SharedPreferences.getInstance(); final key=p.getString('groq_key')??''; final model=p.getString('groq_model')??'llama-3.1-8b-instant'; if(key.isEmpty)return 'Mode local/préparation : configure une clé Groq ou connecte JARVIS NEO PC pour une réponse IA complète. Commande reçue : "$text"'; try { final r=await http.post(Uri.parse('https://api.groq.com/openai/v1/chat/completions'),headers:{'Authorization':'Bearer $key','Content-Type':'application/json'},body:jsonEncode({'model':model,'messages':[{'role':'system','content':'You are JARVIS NEO Mobile. Be concise, helpful and action-oriented.'},{'role':'user','content':text}],'temperature':.4}),); if(r.statusCode==200){final j=jsonDecode(r.body);return j['choices'][0]['message']['content']??'Réponse vide.';} return 'Le fournisseur IA a répondu ${r.statusCode}. Bascule locale recommandée.';}catch(e){return 'Connexion IA indisponible. JARVIS reste en mode local.';} } }

class Prefs { Future<bool> getBool(String k,bool d)async=>(await SharedPreferences.getInstance()).getBool(k)??d; }
class ActivityLog { final entries=<String>[]; void add(String type,String text){entries.insert(0,'$type • $text');if(entries.length>100)entries.removeLast();} }

class DevicesPage extends StatelessWidget { const DevicesPage({super.key}); @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const SectionTitle('Écosystème JARVIS'),DeviceCard('JARVIS NEO PC','Connecté • contrôle complet',Icons.computer,true),DeviceCard('Téléphone','Cet appareil • actif',Icons.smartphone,true),DeviceCard('Google Home','Prêt à connecter',Icons.home_outlined,false),const SizedBox(height:20),Card(child:ListTile(leading:const Icon(Icons.add_link),title:const Text('Ajouter un appareil'),subtitle:const Text('Détection automatique ou code à 6 chiffres'),trailing:const Icon(Icons.chevron_right),onTap:()=>showDialog(context:c,builder:(_)=>const AlertDialog(title:Text('Appairage'),content:Text('La découverte automatique et le code à 6 chiffres sont prévus par le protocole JARVIS NEO.'))))) ]); }
class DeviceCard extends StatelessWidget { final String name,sub; final IconData icon; final bool on; const DeviceCard(this.name,this.sub,this.icon,this.on,{super.key}); @override Widget build(BuildContext c)=>Card(child:ListTile(leading:CircleAvatar(child:Icon(icon)),title:Text(name),subtitle:Text(sub),trailing:Switch(value:on,onChanged:(_){ }))); }

class FilesPage extends StatelessWidget { const FilesPage({super.key}); @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const SectionTitle('Fichiers & IA'),ActionTile('Analyser un fichier','PDF, DOCX, XLSX, PPTX, images et autres formats compatibles',Icons.document_scanner,(){ }),ActionTile('Créer un document','PDF, DOCX, XLSX, PPTX, CSV, TXT',Icons.create_new_folder,(){ }),ActionTile('Convertir / modifier','Traitement local prioritaire pour économiser les tokens',Icons.transform,(){ }),ActionTile('Nettoyer le stockage','Doublons, gros fichiers et éléments inutiles',Icons.cleaning_services,(){ })]); }
class ActionTile extends StatelessWidget { final String title,sub; final IconData icon; final VoidCallback action; const ActionTile(this.title,this.sub,this.icon,this.action,{super.key}); @override Widget build(BuildContext c)=>Card(child:ListTile(contentPadding:const EdgeInsets.all(16),leading:Icon(icon,color:Colors.cyan),title:Text(title),subtitle:Text(sub),trailing:const Icon(Icons.chevron_right),onTap:action)); }

class RoutinesPage extends StatelessWidget { const RoutinesPage({super.key}); @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const SectionTitle('Routines'),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.add),label:const Text('Créer'))]),ActionTile('Mode nuit','Heure + présence + appareil connecté',Icons.nightlight_round,(){}),ActionTile('Arrivée à la maison','Géofence + Wi-Fi + appareils domestiques',Icons.home,(){}),ActionTile('Batterie faible','Économie d’énergie + notifications',Icons.battery_alert,(){}),ActionTile('Routine en langage naturel','Décrire la routine, JARVIS génère le workflow puis demande validation',Icons.auto_awesome,(){} )]); }

class SentinelPage extends StatelessWidget { const SentinelPage({super.key}); @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),border:Border.all(color:Colors.cyan.withOpacity(.3)),gradient:LinearGradient(colors:[Colors.cyan.withOpacity(.12),Colors.transparent])),child:const Row(children:[Icon(Icons.shield,color:Colors.cyan,size:42),SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('SENTINEL',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text('Surveillance intelligente activée')]))])),const SizedBox(height:14),const ActionTile('Confidentialité','Permissions, caméra, micro, localisation et accès applicatifs',Icons.lock_outline,(){ }),const ActionTile('Réseau','Qualité, connexions et anomalies',Icons.wifi_find,(){ }),const ActionTile('Applications','Comportements et accès inhabituels',Icons.apps,(){ }),const ActionTile('Stockage','Analyse des fichiers et risques potentiels',Icons.sd_storage,(){ })]); }

class SettingsPage extends StatefulWidget { final ValueChanged<bool> onTheme; const SettingsPage({super.key,required this.onTheme}); @override State<SettingsPage> createState()=>_SettingsPageState(); }
class _SettingsPageState extends State<SettingsPage>{ final keyCtrl=TextEditingController(); bool voice=true, auto=false; String model='llama-3.1-8b-instant'; @override void initState(){super.initState();load();} Future<void>load()async{final p=await SharedPreferences.getInstance();keyCtrl.text=p.getString('groq_key')??'';voice=p.getBool('voice')??true;auto=p.getBool('auto')??false;model=p.getString('groq_model')??model;setState((){});} Future<void>save()async{final p=await SharedPreferences.getInstance();await p.setString('groq_key',keyCtrl.text.trim());await p.setBool('voice',voice);await p.setBool('auto',auto);await p.setString('groq_model',model);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Paramètres enregistrés')));}
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const SectionTitle('IA & tokens'),TextField(controller:keyCtrl,obscureText:true,decoration:const InputDecoration(labelText:'Clé API Groq',helperText:'Stockée localement. Jamais codée en dur.')),const SizedBox(height:12),DropdownButtonFormField(value:model,decoration:const InputDecoration(labelText:'Modèle cloud'),items:const ['llama-3.1-8b-instant','llama-3.3-70b-versatile','qwen/qwen3-32b'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>model=v!)),SwitchListTile(title:const Text('Voix'),subtitle:const Text('Réponse vocale de JARVIS'),value:voice,onChanged:(v)=>setState(()=>voice=v)),SwitchListTile(title:const Text('Autonomie adaptative'),subtitle:const Text('Choisir automatiquement cloud/local selon le contexte'),value:auto,onChanged:(v)=>setState(()=>auto=v)),const Divider(),const SectionTitle('Sécurité'),const ListTile(leading:Icon(Icons.fingerprint),title:Text('Biométrie + PIN'),subtitle:Text('Déverrouillage et actions sensibles')),const ListTile(leading:Icon(Icons.admin_panel_settings),title:Text('Permissions par application'),subtitle:Text('Accès précis et révocable')),const Divider(),const SectionTitle('Compte & synchronisation'),const ListTile(leading:Icon(Icons.passkey),title:Text('Compte JARVIS NEO'),subtitle:Text('Passkey / biométrie / profils')),const ListTile(leading:Icon(Icons.backup),title:Text('Sauvegarde chiffrée'),subtitle:Text('Sélective, automatique et restaurable')),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('Enregistrer'))]); }

class SectionTitle extends StatelessWidget { final String text; const SectionTitle(this.text,{super.key}); @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Text(text,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold))); }
